feat: new readme for Typescript SDK
pieces-app/pieces-os-client-sdk-for-typescript pull request #29
Opened 2024-04-19 04:55 UTC by Arindam200

2024-04-19 13:20 UTC, shivay-at-pieces requested changes

2024-04-19 13:20 UTC, shivay-at-pieces commented on README.md
> +# <p align="center"> Pieces OS Client SDK For TypeScript
We can add a badge for the documentation

2024-04-22 18:08 UTC, Arindam200 commented on README.md
>  You can get it here: [GitHub Repo](https://github.com/pieces-app/example-typescript)
Yes. Fixed that

2024-07-08 22:39 UTC, mason-at-pieces commented
@shivay-at-pieces @Arindam200 let's get this updated like we did the python readme as well. Anything else that needs fixing here?

2024-07-08 23:02 UTC, shivay-at-pieces approved these changes
@mason-at-pieces this looks good to me

2024-07-09 20:19 UTC, merged